#
# $FreeBSD: doc/en_US.ISO8859-1/articles/new-users/Makefile,v 1.11 2004/08/05 10:04:27 den Exp $
#
# Article: For People New to Both FreeBSD and Unix

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
