#
# $FreeBSD: doc/en_US.ISO8859-1/articles/multi-os/Makefile,v 1.12 2004/04/06 16:10:06 phantom Exp $
#
# Article: Installing and Using FreeBSD With Other Operating Systems

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
