#
# $FreeBSD: doc/en_US.ISO8859-1/articles/contributing/Makefile,v 1.6 2004/07/06 15:09:51 hrs Exp $
#
# Article: Contributing to FreeBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
