#
# Build the Handbook with just the content from this chapter.
#
# Original revision: 1.1
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/kernelconfig/Makefile,v 1.1 2004/09/26 05:20:36 hrs Exp $
#

CHAPTERS= 	kernelconfig/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
