#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/zh_TW.Big5/books/handbook/virtualization/Makefile,v 1.1 2007/10/12 17:41:09 chinsan Exp $
#

CHAPTERS= 	virtualization/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
