# 
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.4
#
# $FreeBSD: doc/zh_CN.GB2312/articles/Makefile.inc,v 1.1 2005/03/20 15:30:30 delphij Exp $
#

DESTDIR?=	${DOCDIR}/zh_CN.GB2312/articles/${.CURDIR:T}
