#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.52
#
# $FreeBSD: doc/zh_CN.GB2312/articles/Makefile,v 1.7 2008/11/17 08:00:30 loader Exp $

SUBDIR =
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= linux-users
SUBDIR+= nanobsd
SUBDIR+= rc-scripting
SUBDIR+= remote-install

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
