#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/zh_TW.Big5/books/developers-handbook/kerneldebug/Makefile,v 1.1 2006/06/17 10:22:43 vanilla Exp $
#

CHAPTERS= 	kerneldebug/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
