#
# $FreeBSD: doc/en_US.ISO8859-1/articles/relaydelay/Makefile,v 1.1 2004/06/21 20:44:14 trhodes Exp $
#
# Article: Using greylisting with FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
