# $FreeBSD: doc/zh_TW.Big5/articles/cvs-freebsd/Makefile,v 1.1 2006/01/08 03:04:39 vanilla Exp $
#
# Article: Setting up a CVS repository - the FreeBSD way
#
# Build the Traditional Chinese Version

MAINTAINER= stijn@win.tue.nl

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
