#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: 1.1
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/mirrors/Makefile,v 1.2 2006/03/15 19:38:55 delphij Exp $
#

CHAPTERS= 	mirrors/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
