# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/5-roadmap/Makefile,v 1.4 2004/04/06 16:10:02 phantom Exp $
#
# Article: FreeBSD 5-STABLE roadmap

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

CSS_SHEET_ADDITIONS= extra.css

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
