#!/bin/sh

# $Wintelcom: src/freebsd/pxe/doc/pre,v 1.1 2000/07/14 12:42:05 bright Exp $
# $FreeBSD: doc/en_US.ISO8859-1/articles/pxe/pre,v 1.1 2003/06/17 15:34:24 alfred Exp $

echo pre-install
exit 0
