#
# $FreeBSD: doc/en_US.ISO8859-1/articles/contributing-ports/Makefile,v 1.1 2005/10/17 05:52:59 linimon Exp $
#
# Article: Contributing to the FreeBSD Ports Collection

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
