#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: 1.1
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/geom/Makefile,v 1.1 2005/08/28 17:07:51 delphij Exp $
#

CHAPTERS= 	geom/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
