#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/en_US.ISO8859-1/books/handbook/audit/Makefile,v 1.1 2005/08/06 03:22:18 trhodes Exp $
#

CHAPTERS= 	audit/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
