#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/zh_TW.Big5/books/handbook/boot/Makefile,v 1.2 2006/01/31 01:31:02 vanilla Exp $
# Original revision: 1.1
#

CHAPTERS= 	boot/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
