#
# $FreeBSD: doc/en_US.ISO8859-1/articles/explaining-bsd/Makefile,v 1.6 2004/07/06 15:09:52 hrs Exp $
#
# Article: Explaining BSD

MAINTAINER=grog@FreeBSD.org

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
