#
# $FreeBSD: doc/en_US.ISO8859-1/articles/console-server/Makefile,v 1.5 2004/08/05 10:04:26 den Exp $
#
# Article: Console Server

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml
IMAGES_EN=	tk0231-9-1.png

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
