#
# The FreeBSD Simplified Chinese Project
#
# Original Revision: 1.14
# $FreeBSD: doc/zh_CN.GB2312/books/Makefile,v 1.3 2006/03/15 19:57:48 delphij Exp $

SUBDIR = arch-handbook
SUBDIR+= handbook
SUBDIR+= porters-handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
