# $FreeBSD: doc/zh_TW.Big5/articles/Makefile,v 1.6 2008/05/19 06:50:08 chinsan Exp $

SUBDIR =
SUBDIR+= contributing
SUBDIR+= cvs-freebsd
SUBDIR+= freebsd-questions
SUBDIR+= hubs
SUBDIR+= mailing-list-faq
SUBDIR+= nanobsd
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports
SUBDIR+= remote-install

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
