#
# $FreeBSD: doc/en_US.ISO8859-1/articles/freebsd-questions/Makefile,v 1.6 2004/08/05 10:04:27 den Exp $
#
# Article: How to get best results from the FreeBSD-questions mailing list

MAINTAINER=grog@FreeBSD.org

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
