#
# $FreeBSD: doc/zh_TW.Big5/articles/pr-guidelines/Makefile,v 1.1 2006/06/17 10:22:42 vanilla Exp $
#
# Article: Problem Report Handling Guidelines

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
