#
# $FreeBSD: doc/en_US.ISO8859-1/articles/cvsup-advanced/Makefile,v 1.5 2004/04/06 16:10:03 phantom Exp $
#
# Article: CVSup Advanced Points

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
