#
# $FreeBSD: doc/en_US.ISO8859-1/articles/building-products/Makefile,v 1.2 2005/11/20 16:08:21 jkoshy Exp $
#
# Article: Building products using FreeBSD

DOC?=			article

FORMATS?=		html

INSTALL_COMPRESSED?=	gz
INSTALL_ONLY_COMPRESSED?=

SRCS=			article.sgml

IMAGES_EN=		freebsd-branches.pic freebsd-organization.pic

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
