#
# $FreeBSD: doc/en_US.ISO8859-1/articles/storage-devices/Makefile,v 1.4 2004/04/06 16:10:08 phantom Exp $
#
# Article: Storage Devices

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
