#
# $FreeBSD: doc/zh_TW.Big5/articles/mailing-list-faq/Makefile,v 1.1 2006/06/17 10:22:42 vanilla Exp $
#
# Article: Frequently Asked Questions About The FreeBSD Mailing Lists

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

# 
# SRCS lists the individual SGML files that make up the document. Changes
# to any of these files will force a rebuild
#

# SGML content
SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
