#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/en_US.ISO8859-1/books/handbook/advanced-networking/Makefile,v 1.2 2004/06/03 07:04:51 trhodes Exp $
#

CHAPTERS= 	advanced-networking/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
