#
# Build the Handbook with just the content from this chapter.
#
# The FreeBSD Simplified Chinese Project
# Original Revision: 1.1
#
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/virtualization/Makefile,v 1.1 2007/04/17 03:12:07 delphij Exp $
#

CHAPTERS= 	virtualization/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
