# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/casestudy-argentina.com/Makefile,v 1.1 2005/08/30 00:00:25 murray Exp $
#
# Article: Casestudy from Argentina.com

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
