# $FreeBSD: doc/zh_TW.Big5/Makefile,v 1.9 2006/07/11 13:18:28 hrs Exp $

SUBDIR = articles
SUBDIR += books

COMPAT_SYMLINK=	zh_TW

DOC_PREFIX = ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
