#
# Build the Handbook with just the content from this chapter.
#
# Original revision: 1.1
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/firewalls/Makefile,v 1.1 2005/04/05 17:27:49 delphij Exp $
#

CHAPTERS= 	firewalls/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
