# $FreeBSD: doc/en_US.ISO8859-1/Makefile,v 1.7 1999/09/06 06:52:34 peter Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = en

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
