#
# $FreeBSD: doc/en_US.ISO8859-1/articles/diskless-x/Makefile,v 1.8 2004/04/06 16:10:03 phantom Exp $
#
# Article: Diskless X Server: a how to guide

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
