# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/geom-class/Makefile,v 1.1 2005/08/29 23:54:30 murray Exp $
#
# Article: Writing a GEOM Class

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
