#
# $FreeBSD: doc/en_US.ISO8859-1/articles/checkpoint/Makefile,v 1.8 2006/02/20 20:53:00 jcamou Exp $
#
# Article: Integration of Check Point Firewall-1 and FreeBSD IPsec

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml
IMAGES_EN=	networks.pic

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
