# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/wp-toolbox/Makefile,v 1.1 2006/02/13 08:21:21 murray Exp $
#
# Article: Casestudy about FreeBSD as a Software Testing Toolbox

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
