#
# $FreeBSD: doc/en_US.ISO8859-1/articles/portbuild/Makefile,v 1.1 2004/06/12 23:10:34 marcus Exp $
#
# Article: Portbuild Procedure
#

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
