#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: 1.1
# $FreeBSD: doc/zh_CN.GB2312/books/handbook/printing/Makefile,v 1.1 2004/09/26 05:20:37 hrs Exp $
#

CHAPTERS= 	printing/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
