# 
# The FreeBSD Traditional Chinese Project
#
# Original Revision: 1.2
# $FreeBSD: doc/zh_TW.Big5/articles/nanobsd/Makefile,v 1.1 2006/07/09 14:03:00 vanilla Exp $
#
# Article: Introduction to NanoBSD

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

# Images from the cross-document image library
IMAGES_LIB=  callouts/1.png
IMAGES_LIB+= callouts/2.png
IMAGES_LIB+= callouts/3.png
IMAGES_LIB+= callouts/4.png

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
