# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/committers-guide/Makefile,v 1.10 2004/08/17 15:12:58 jhb Exp $
#
# Article: The FreeBSD Committers Guide

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
