# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/releng-packages/Makefile,v 1.4 2004/04/06 16:10:07 phantom Exp $
#
# Article: FreeBSD Release Engineering of Third Party Software Packages

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

CSS_SHEET_ADDITIONS= extra.css

DOC_PREFIX?= ${.CURDIR}/../../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
