# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/version-guide/Makefile,v 1.3 2005/08/17 14:27:51 linimon Exp $
#
# Article: FreeBSD Version Guide

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
