#
# $FreeBSD: doc/en_US.ISO8859-1/articles/dialup-firewall/Makefile,v 1.5 2004/08/05 10:04:26 den Exp $
#
# Article: Dialup firewalling with FreeBSD

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
