# 
# $FreeBSD: doc/en_US.ISO8859-1/articles/p4-primer/Makefile,v 1.1 2005/11/24 20:03:47 blackend Exp $
#
# Perforce in FreeBSD Development article.

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
