#
# $FreeBSD: doc/en_US.ISO8859-1/articles/serial-uart/Makefile,v 1.6 2004/08/05 10:04:28 den Exp $
#
# Article: Serial and UART Tutorial

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
