#
# $FreeBSD: doc/zh_TW.Big5/articles/freebsd-questions/Makefile,v 1.1 2006/07/09 03:19:08 vanilla Exp $
# Original revision: 1.6
#
# Article: How to get best results from the FreeBSD-questions mailing list

MAINTAINER=chinsan.tw@gmail.com

DOC?= article

FORMATS?= html
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.sgml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
