# $FreeBSD: doc/zh_TW.Big5/books/Makefile,v 1.7 2006/06/17 10:22:43 vanilla Exp $

SUBDIR = developers-handbook
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook
#SUBDIR+= zh-tut

ROOT_SYMLINKS = faq fdp-primer handbook porters-handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
