# $FreeBSD: doc/en_US.ISO8859-1/books/Makefile,v 1.14 2005/06/18 18:54:54 niklas Exp $

SUBDIR = arch-handbook
SUBDIR+= corp-net-guide
SUBDIR+= design-44bsd
SUBDIR+= dev-model
SUBDIR+= developers-handbook
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= pmake
SUBDIR+= porters-handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
