#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/zh_TW.Big5/books/handbook/network-servers/Makefile,v 1.1 2006/01/06 09:15:38 vanilla Exp $
#

CHAPTERS= 	network-servers/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
