# Original Revision: 1.7
# $FreeBSD: doc/zh_CN.GB2312/Makefile,v 1.3 2006/07/11 13:18:56 hrs Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK=	zh_CN

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
