#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/en_US.ISO8859-1/books/handbook/virtualization/Makefile,v 1.1 2007/04/06 07:36:19 murray Exp $
#

CHAPTERS= 	virtualization/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
